# SPDX-FileCopyrightText: 2020 Andreas Bauer
#
# SPDX-License-Identifier: MIT

name: REUSE Compliance

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1.0
      with:
        cmd: lint
